services:

  mysql:
    image: mysql:8.4
    command:
      - --mysql-native-password=ON
    ports:
      - "13314:3306" # sequel用
    volumes:
      - ./storage/mysql/data:/var/lib/mysql:cached
      - ./docker/mysql:/docker-entrypoint-initdb.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kintone

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/kintone
    working_dir: /var/www/kintone
    stdin_open: true
